services:
  - type: web
    name: pebly-backend
    env: java
    buildCommand: cd url-service && mvn clean package -DskipTests
    startCommand: cd url-service && java -Dspring.profiles.active=prod -Dserver.port=$PORT -jar target/url-service-1.0.0.jar
    plan: starter
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: pebly-database
      - key: FRONTEND_URL
        value: https://pebly.vercel.app
      - key: SHORT_URL_DOMAIN
        value: https://links.pdfcircle.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        value: rzp_live_RWtmHyTZfva7rb
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: -Dspring.profiles.active=prod
      - key: CACHE_TYPE
        value: simple
      - key: BACKEND_URL
        value: https://urlshortner-1-hpyu.onrender.com
      - key: ACCEPT_ALL_HOSTS
        value: true